- name: Launch instances
  local_action: gce 
  args:
    instance_names: "{{ cloud['instance_names'] }}"
    machine_type: "{{ cloud['machine_type'] }}"
    image: "{{ cloud['image'] }}"
    service_account_email: "{{ cloud['service_account_email'] }}"
    pem_file: "{{ cloud['pem_file'] }}"
    project_id: "{{ cloud['project_id'] }}"
    tags: master
  register: gce

- name: Wait for SSH to come up
  wait_for: host={{ item.public_ip }} port=22 delay=10 timeout=60
  with_items: gce.instance_data

- name: Add instances to master group
  local_action: add_host hostname={{ item.public_ip }} groupname=master
  with_items: gce.instance_data 
